version: '2'
services:
    ngapp-app:
        image: ngapp
        external_links:
            - ngapp-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ngapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ngapp-mysql:
        extends:
            file: mysql.yml
            service: ngapp-mysql
